version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "7439:5432"

  redis:
    image: redis
    container_name: napims_cache
  app:
    image: rightclicksolutions/napims360:master
    build:
      context: .

    environment:
      # Database settings
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      DB_NAME: ${DB_NAME}

      # Django settings
      ADMIN_PASSWORD: admin

      # local settings
      CSRF_COOKIE_DOMAIN: napims360.local
      DJANGO_USE_CACHE: "true"
      LOGGING_FORMATTER: verbose
      CUSTOM_UWSGI_SERVE_STATIC: "false"
      REDIS_URL: ${REDIS_URL}

      USE_CLOUDINARY: ${USE_CLOUDINARY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: apikey
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_FROM_USER: ${EMAIL_FROM_USER}

      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_CONNECTION_NAME: ${AUTH0_CONNECTION_NAME}
      AUTH0_API_ID: ${AUTH0_API_ID}

    volumes:
      # external folders
      - /tmp/napims360-static:/var/www/static

    ports:
      - 8001:8000  # web server

volumes:
  pgdata:
