# Generated by Django 3.1.7 on 2021-07-29 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='date_discovered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='date_drilled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flowline',
            name='date_commissioned',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowline',
            name='date_completed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='omloperator',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='available_capacity',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='spud_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
