# Generated by Django 3.1.7 on 2021-08-02 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0002_auto_20210729_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='OilField',
        ),
        migrations.RenameField(
            model_name='reservoir',
            old_name='field',
            new_name='oil_field',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='field',
            new_name='oil_field',
        ),
    ]
