# Generated by Django 3.1.7 on 2021-08-02 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_auto_20210802_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetupgrade',
            name='date_of_upgrade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='data_of_exploration_completion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='lat',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='lng',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oilfield',
            name='terrain',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
