# Generated by Django 3.1.7 on 2021-08-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_auto_20210802_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='network',
        ),
        migrations.RemoveField(
            model_name='flowline',
            name='network',
        ),
        migrations.RemoveField(
            model_name='trunkline',
            name='network',
        ),
    ]
