# Generated by Django 3.1.7 on 2021-08-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_auto_20210802_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oml',
            name='shore_type',
        ),
    ]
